[package]
name = "call_python_inside_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3-build-config = "0.18.1"

[dependencies.pyo3]
version = "0.18.0"
features = ["auto-initialize"]
